# Generated by Django 3.1 on 2020-08-30 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('referenceId', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('descirption', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='articleExpiryDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiryDate', models.DateField()),
                ('referenceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockReading.article')),
            ],
            options={
                'unique_together': {('referenceId', 'expiryDate')},
            },
        ),
    ]
